name: befr_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  lib: ^0.0.3
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
  - family: Pacifico
    fonts:
      - asset: fonts/Pacifico-Regular.ttf
        weight: 700
  - family: Lobster
    fonts:
      - asset: fonts/Lobster-Regular.ttf
        weight: 500

assets:
  - assets/icons/


